# Allow configuration of autocert without installing step-certificates.
{{- if not (index .Values "step-certificates" "enabled") }}
apiVersion: v1
kind: Secret
type: smallstep.com/provisioner-password
metadata:
  name: {{ .Release.Name }}-step-certificates-provisioner-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autocert.labels" . | nindent 4 }}
  annotations:
    vaultInjectionChecksum: {{ .Values.ca.provisioner.password | sha256sum }}
{{- if .Values.ca.provisioner.secretAnnotations }}
{{ toYaml .Values.ca.provisioner.secretAnnotations | indent 4 }}
{{- end }}
data:
  password: {{ .Values.ca.provisioner.password | b64enc }}
{{- end }}
